version: '3'

services:
  backend:
    image: backend
    build:
      context: ./backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    env_file:
      - .env
      - /opt/elasticbeanstalk/deployment/env.list
    

  frontend:
    image: frontend
    build:
      context: ./frontend-react
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "${EXPOSED_FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    depends_on:
      - backend
